release artifacts for release v0.5.2
aws-controllers-k8s/sagemaker-controller pull request #192
Opened 2023-01-13 19:13 UTC by ananth102

Issue #, if available:

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-13 19:14 UTC, ananth102 commented
/hold until tuesday

2023-01-14 23:36 UTC, surajkota commented
Bump version to 0.6.0 since we are adding feature

2023-01-30 06:08 UTC, AlmogBaku commented
any update?

2023-01-30 06:11 UTC, AlmogBaku requested changes

2023-01-30 06:11 UTC, AlmogBaku commented on helm/Chart.yaml
> +appVersion: v0.5.2
```suggestion
version: v0.6.0
appVersion: v0.6.0
```

2023-01-30 06:11 UTC, AlmogBaku commented on helm/templates/NOTES.txt
> +This chart deploys "public.ecr.aws/aws-controllers-k8s/sagemaker-controller:v0.5.2".
```suggestion
This chart deploys "public.ecr.aws/aws-controllers-k8s/sagemaker-controller:v0.6.0".
```

2023-02-02 23:41 UTC, surajkota commented
/close since 0.6 is released

2023-02-03 00:44 UTC, closed without merging