Removing check for pending state in Model Package test
aws-controllers-k8s/sagemaker-controller pull request #235
Opened 2023-04-06 21:53 UTC by ananth102

Issue #, if available:

Description of changes:

Model Package can sometimes reach scheduled state before the controller can verify that it is in Pending state. This PR removes the check for pending/resource synced.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-06 22:08 UTC, ryansteakley commented
Why is the code change in model-monitor but everything else references model-package?

2023-04-06 22:09 UTC, ananth102 commented
> Why is the code change in model-monitor but everything else references model-package?

My bad, resource names were too similar.

2023-04-06 22:30 UTC, ryansteakley approved these changes

2023-04-06 23:00 UTC, surajkota requested changes

2023-04-06 23:00 UTC, surajkota commented on test/e2e/tests/test_monitoring_schedule.py
>          self._assert_monitoring_schedule_status_in_sync(
do we need to increase wait time for this check?

also can we do the same for feature group?

2023-04-06 23:26 UTC, ananth102 commented
/hold

2023-04-07 01:30 UTC, surajkota requested changes
change for training as well - https://github.com/aws-controllers-k8s/sagemaker-controller/blob/45842199d81ed8b73f36dffe28396c269ae45ec5/test/e2e/tests/test_trainingjob.py#L64

lgtm otherwise

2023-04-07 04:15 UTC, surajkota commented
/approve

2023-04-07 16:26 UTC, ananth102 commented
/unhold

2023-04-07 18:56 UTC, ryansteakley commented
/lgtm

2023-04-07 18:57 UTC, merged