Feature group sample
aws-controllers-k8s/sagemaker-controller pull request #46
Opened 2021-06-21 17:43 UTC by BriannaRoskind

Added a feature group sample subdirectory, README, and sample code.

This PR assumes feature group testing code from PR #45, is already in place.

2021-07-07 19:45 UTC, akartsky commented on samples/feature_group/README.md
> +First create an Amazon SageMaker execution role, and then [here are directions](https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store-adding-policies.html) to give your SageMaker Execution Ro
This section is not required 

in the pre-req we already show them how to create IAM role and give SagemakerFullAccess and S3FullAccess

2021-07-07 19:50 UTC, akartsky commented on samples/feature_group/README.md
> +## Create an S3 bucket:
these should be subheadings in Prerequisites
so use `###`

2021-07-07 19:51 UTC, akartsky commented on samples/feature_group/README.md
> +
we need a section explaining the yaml changes that they need to make

2021-07-07 19:51 UTC, akartsky commented on samples/feature_group/README.md
> +`$ kubectl apply ``-``f ``my``-``feature-group``.``yaml``
not formatted properly

2021-07-07 19:52 UTC, akartsky commented on samples/feature_group/README.md
> +## Ingesting Data into your Feature Group
need to mention that ingestion is not supported in the controller

2021-07-07 19:53 UTC, akartsky commented on samples/feature_group/README.md
> +```
this whole section is not formatted properly

2021-07-07 19:54 UTC, akartsky commented on samples/feature_group/my-feature-group.yaml
> +	featureType: Integral
improper indentation using tab instead of space

2021-07-07 19:55 UTC, akartsky commented on samples/feature_group/my-feature-group.yaml
> +  name: ack-sample-feature-group-<your user name>
follow the convention from other samples  
use capital <YOUR JOB NAME>

2021-07-07 19:56 UTC, akartsky commented on samples/feature_group/my-feature-group.yaml
> +                           AmazonS3FullAccess,
follow the convention from other samples

2021-07-08 17:30 UTC, akartsky approved these changes

2021-07-08 17:32 UTC, akartsky commented
/approve cancel

2021-07-16 02:05 UTC, surajkota requested changes

2021-07-16 02:05 UTC, surajkota commented on samples/feature_group/README.md
> +records = []
use the faster run option make this a script instead of readme and add the commands here to run it. Take file location as an input

2021-07-16 02:05 UTC, surajkota commented on samples/feature_group/README.md
> +This sample demonstrates how to create a feature group using the Amazon AWS Controllers for Kubernetes (ACK) service controller for Amazon SageMaker.
If this is taken from a notebook, can you please add a reference to it?

It'll be useful for us as well. We need to start doing it for all samples

2021-07-16 23:36 UTC, akartsky commented
/lgtm

2021-07-17 00:07 UTC, merged

2021-07-17 02:13 UTC, surajkota commented
/approve